### ISSUE TITLE
database already exists

### ISSUE THREAD

**Issue by jjuu** [emirozer/fake2db#48]
I inserted 10000 to the db named fake. Then I want to insert another 10000. But error happened.

> fake2db --rows 10000 --db postgresql --name fake --username postgres 
> 2019-03-18 09:55:19,907 www      Rows argument : 20000
> 2019-03-18 09:55:20,036 www      database "fake" already exists
> 
> Traceback (most recent call last):
>   File "/home/www/pyenv/aws/bin/fake2db", line 11, in <module>
>     sys.exit(main())
>   File "/home/www/pyenv/aws/local/lib/python2.7/site-packages/fake2db/fake2db.py", line 167, in main
>     number_of_rows=args.rows, name=args.name, custom=custom)
>   File "/home/www/pyenv/aws/local/lib/python2.7/site-packages/fake2db/postgresql_handler.py", line 18, in fake2db_initiator
>     cursor, conn = self.database_caller_creator(number_of_rows, **connection_kwargs)
>   File "/home/www/pyenv/aws/local/lib/python2.7/site-packages/fake2db/postgresql_handler.py", line 46, in database_caller_creator
>     cur.execute('CREATE DATABASE %s;' % dbname)
> psycopg2.ProgrammingError: database "fake" already exists

Thanks for your great work.

**Comment by emirozer** [comment]
ah yes this is a fix that i will apply when i have some time this weekend. thx for reporting
