### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'execute'

### ISSUE THREAD

**Issue by ericdorsey** [emirozer/fake2db#8]
Cool idea; wanted to play with this. 

OSX 10.9.5
MySQL 5.5.38
Python 2.7.5

Installed [http://dev.mysql.com/downloads/connector/python/](http://dev.mysql.com/downloads/connector/python/)

Opened new terminal  (iTerm2) session 

Ran 
```$ fake2db --rows 200 --db mysql```

Got:
```
Traceback (most recent call last):
  File "/usr/local/bin/fake2db", line 8, in <module>
    load_entry_point('fake2db==0.1.5', 'console_scripts', 'fake2db')()
  File "/Library/Python/2.7/site-packages/fake2db/fake2db.py", line 106, in main
    fake_mysql_handler.fake2db_mysql_initiator(host, port, int(args.rows))
  File "/Library/Python/2.7/site-packages/fake2db/mysql_handler.py", line 42, in fake2db_mysql_initiator
    cursor.execute(tables[key])
AttributeError: 'NoneType' object has no attribute 'execute'
```

Any thoughts?  Thanks!

**Comment by xiaohanyu** [comment]
Seems there's no password for postgres handler?
